In [12]:
import numpy as np
x = np.array([ [  1,  2,  3, 5],
             [   1 , 4,  1, 2],
             [   1 , 3,  2, 2] ])
             
b = np.array( [ [ 2, 3, 1, 5],  [ 1, 2, 4 , 2] ] )

Y = np.zeros((3, 2))


# print( np.dot ( x, b.T ))

for i  in range(2):
    print(b[i])
    Y[ :,i]  =  np.dot(x, b[i])
    

print(Y)
    
print( np.dot ( x, b.T ))    


             

[2 3 1 5]
[1 2 4 2]
[[36. 27.]
 [25. 17.]
 [23. 19.]]
[[36 27]
 [25 17]
 [23 19]]


In [13]:
max_indices = np.argmax(x, axis=1)
print(max_indices)

[3 1 1]


In [16]:
print(np.amax(x, axis=1))

[5 4 3]


In [23]:
M = np.zeros(3)
for i  in range(len(max_indices)):
    M[i] = x[i , max_indices[i]]
print(M)    

[5. 4. 3.]


In [24]:
if M.ndim == 1:
    M = M[None]  # promote to 2-dimensions
print(M)    


[[5. 4. 3.]]


In [29]:

r = np.random.rand(2, 10, 10) 

rb = np.reshape(r, (5, 5, 8)) 

print(rb)


[[[0.03217479 0.35340906 0.5573612  0.2843961  0.38425623 0.80573951
   0.2575449  0.04327162]
  [0.00526912 0.66016783 0.37814405 0.08017069 0.96114082 0.92542539
   0.90258716 0.27226898]
  [0.06636345 0.81656012 0.30173281 0.3599995  0.61733985 0.02761273
   0.11360677 0.5667839 ]
  [0.15103271 0.29815096 0.62808855 0.8021461  0.24272237 0.24493012
   0.0441164  0.82789137]
  [0.13802424 0.63805234 0.17497711 0.18944875 0.47295023 0.57842921
   0.6571463  0.79752703]]

 [[0.19451754 0.02042436 0.55405765 0.65800986 0.42596687 0.24733894
   0.04512521 0.64737193]
  [0.73629663 0.94211805 0.78004864 0.36052426 0.34741446 0.88647904
   0.33223554 0.45111738]
  [0.25238705 0.08990403 0.68194867 0.91970052 0.43606585 0.43020651
   0.08121815 0.03352625]
  [0.46872585 0.67376694 0.86943773 0.7098483  0.32298891 0.10732476
   0.76706072 0.46560107]
  [0.87965281 0.69866317 0.73775221 0.76738569 0.73065525 0.22714235
   0.36688259 0.52133864]]

 [[0.50315266 0.55428301 0.80595579 0.05696571

In [66]:
X = np.arange(2,5)
print(X)
print(X.ndim)
# m , = X.shape
X_poly = np.zeros((X.shape[0], 6))
print(X_poly )

[2 3 4]
1
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [67]:
Y = X[:, np.newaxis]
print(Y)
print(Y.ndim)

[[2]
 [3]
 [4]]
2


In [64]:
for i in range(0, 6):
    X_poly[:, i] = Y[:,0] ** (i + 1)
np.set_printoptions(precision=4,suppress=True)    
print( X_poly)

[[   2.    4.    8.   16.   32.   64.]
 [   3.    9.   27.   81.  243.  729.]
 [   4.   16.   64.  256. 1024. 4096.]]


In [65]:
for i in range(0, 6):
    X_poly[:, i] = X ** (i + 1)
np.set_printoptions(precision=4,suppress=True)    
print( X_poly)

[[   2.    4.    8.   16.   32.   64.]
 [   3.    9.   27.   81.  243.  729.]
 [   4.   16.   64.  256. 1024. 4096.]]


In [2]:
import numpy as np
 
# initializing points in
# numpy arrays
point1 = np.array([1, 1])
point2 = np.array([3, 3])
 
# finding sum of squares
sum_sq = np.sum(np.square(point1 - point2))
 
# Doing squareroot and
# printing Euclidean distance
print(np.sqrt(sum_sq))

2.23606797749979


In [15]:
point1 = np.array([5.65858312, 4.79996405])
initial_centroids = np.array([[3, 3], [6, 2], [8, 5]])
for y in range(3):
    point2 = initial_centroids[y]              
    distance = np.sqrt( np.sum(np.square(point1 - point2)) )
    print(distance)


3.2105972633205395
2.8207027789615364
2.349946251989891


In [27]:
X = np.array([[1.84207953, 4.6075716 ],[1.9, 4.5 ],
 [5.65858312, 4.79996405], [ 8.9, 4.9],
 [6.35257892, 3.2908545 ]] )

m, n = X.shape

K = 3   # 3 Centroids
centroids = np.array([[3, 3], [6, 2], [8, 5]])
distances = np.zeros( ( m, K) )
for i in range(m):
        point1 = X[i]        
        for y in range(K):
            point2 = centroids[y]
            distances[i,y] = np.sqrt( np.sum(np.square(point1 - point2)) )

print(distances)
idx = np.argmin(distances, axis=1)
print(idx)


centroids = np.zeros((K, n))
counter = np.zeros((K, 1))
# ====================== YOUR CODE HERE ======================
for i in range(m):
    centroids[ idx[i] ] = centroids[ idx[i] ]  + X[i]
    counter[  idx[i] ] =  counter[  idx[i] ]  + 1

for i in range(K):
    if counter[i] == 0:
        counter[i] = 1
        
    
print(centroids)
print(counter)

centroids = centroids / counter

print(centroids)



[[1.981178   4.90792546 6.17041203]
 [1.86010752 4.80208288 6.1204575 ]
 [3.21059726 2.82070278 2.34994625]
 [6.19838689 4.10121933 0.90553851]
 [3.36517188 1.33813947 2.37385226]]
[0 0 2 2 1]
[[ 3.74207953  9.1075716 ]
 [ 6.35257892  3.2908545 ]
 [14.55858312  9.69996405]]
[[2.]
 [1.]
 [2.]]
[[1.87103976 4.5537858 ]
 [6.35257892 3.2908545 ]
 [7.27929156 4.84998203]]


In [32]:
randidx = np.random.permutation(X.shape[0])
print(randidx)

[4 3 0 2 1]


In [39]:
rand_indices = np.random.choice(5, 3, replace=False)
print(rand_indices)

centroids =    X[rand_indices, :]
print(centroids)

[2 1 0]
[[5.65858312 4.79996405]
 [1.9        4.5       ]
 [1.84207953 4.6075716 ]]
