In [9]:
import numpy as np
X = np.array([ [  1,  5, 3, 2],
             [   1 , 4,  1, 2],
             [   1 , 3,  2, 2] ])
X_mean = np.mean(X , axis = 0)

print(X_mean)

[1. 4. 2. 2.]


In [10]:
np.mean(X , axis = 1)

array([2.75, 2.  , 2.  ])

In [13]:
sorted_index = np.argsort(X[0])[::]
print(sorted_index)

[0 3 2 1]


In [14]:
X[:,sorted_index]

array([[1, 2, 3, 5],
       [1, 2, 1, 4],
       [1, 2, 2, 3]])

In [15]:
X[1][sorted_index]

array([1, 2, 1, 4])

In [3]:
import numpy as np
x=np.array([12,43,2,100,54,5,68])
print(np.argsort(x))
#get two highest value index of array
print(np.argsort(x)[-2:])


[2 5 0 1 4 6 3]
[6 3]


In [4]:
print(np.argsort(x)[::])

[2 5 0 1 4 6 3]


In [7]:
sorted_index = np.argsort(x)[::-1]
print(sorted_index)

[3 6 4 1 0 5 2]


In [8]:
print( x [sorted_index])

[100  68  54  43  12   5   2]


In [10]:
print( np.sort(x ))

[  2   5  12  43  54  68 100]


In [11]:
print( np.sort(x )[::-1])

[100  68  54  43  12   5   2]
